### ISSUE TITLE
Import Error when importing correlation_cuda

### ISSUE THREAD

**Issue by StefanBaar** [baowenbo/DAIN#46]
I get the following Error when importing correlation_cuda in python 3.6 and python 2.7 with torch 1.4.0 and 1.1.0:

`/usr/local/lib/python3.6/dist-packages/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg/correlation_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE`

the other modules from the my_package directories work fine.

**Comment by wang99711123** [comment]
Did you solve this problem?
I meet the same problem when importing filterinterpolation_cuda.

**Comment by StefanBaar** [comment]
> Did you solve this problem?
> I meet the same problem when importing filterinterpolation_cuda.

No I couldn’t solve it yet. But I don’t have a problem wit filterinterpolation_cuda. 

What error do you get?

**Comment by wang99711123** [comment]
Traceback (most recent call last):
&nbsp; File "train.py", line 15, in <module&gt;
&nbsp;&nbsp;&nbsp; import networks
&nbsp; File "/home/ygao/wzf/DAIN/networks/__init__.py", line 1, in <module&gt;
&nbsp;&nbsp;&nbsp; from .DAIN import DAIN
&nbsp; File "/home/ygao/wzf/DAIN/networks/DAIN.py", line 4, in <module&gt;
&nbsp;&nbsp;&nbsp; from my_package.FilterInterpolation import&nbsp; FilterInterpolationModule
&nbsp; File "/home/ygao/wzf/DAIN/my_package/FilterInterpolation/__init__.py", line 1, in <module&gt;
&nbsp;&nbsp;&nbsp; from .FilterInterpolationModule import *
&nbsp; File "/home/ygao/wzf/DAIN/my_package/FilterInterpolation/FilterInterpolationModule.py", line 6, in <module&gt;
&nbsp;&nbsp;&nbsp; from .FilterInterpolationLayer import FilterInterpolationLayer,WeightLayer, PixelValueLayer,PixelWeightLayer,ReliableWeightLayer
&nbsp; File "/home/ygao/wzf/DAIN/my_package/FilterInterpolation/FilterInterpolationLayer.py", line 4, in <module&gt;
&nbsp;&nbsp;&nbsp; import filterinterpolation_cuda as my_lib
ImportError: /home/ygao/anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/filterinterpolation_cuda-0.0.0-py3.6-linux-x86_64.egg/filterinterpolation_cuda.cpython-36m-x86_64-linux-gnu.so:
&nbsp;undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs


The above is the program error.
The possible reason I see in google is ”This may be your CUDA version is not compilable with your PyTorch version“.But I copied the virtual environment using “environment.yaml”which is provided.I don't think the problem lies here.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"stefanbaar"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月23日(星期天) 晚上7:16
收件人:&nbsp;"baowenbo/DAIN"<DAIN@noreply.github.com&gt;;
抄送:&nbsp;"wzf"<305950337@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [baowenbo/DAIN] Import Error when importing correlation_cuda (#46)



 
Did you solve this problem?
 I meet the same problem when importing filterinterpolation_cuda.
  
No I couldn’t solve it yet. But I don’t have a problem wit filterinterpolation_cuda.
 
What error do you get?

**Comment by StefanBaar** [comment]
Ok, I was able to resolve the issue by:

-- compiling pytorch 1.4.0 from source 
-- uninstalling correlation_cuda (sudo pip3 uninstall correlation-cuda) 
-- reinstalling correlation_cuda (sudo rm -rf build *.egg-info dist && sudo python3 setup.py install)
